version: "3.7"
services:
  web:
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/medium_dev
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: './run.sh'
  db:
      env_file: ./.env
      image: postgres:12.0-alpine
      volumes:
              - postgres_data:/var/lib/postgresql/data/
      environment:
              - POSTGRES_USER=${SQL_USER}
              - POSTGRES_PASSWORD=${SQL_PASSWORD}
              - POSTGRES_DB=${SQL_NAME}
volumes:
  postgres_data: