version: "3.7"
services:
  web:
    build:
      context: .
    env_file: ./.env    
    volumes: 
      - .:/home/app
    depends_on:
      - db
    ports:
      - "4000:4000"
    
  db:
      env_file: ./.env
      image: postgres:12.0-alpine
      volumes:
              - postgres_data:/var/lib/postgresql/data/
      environment:
              - POSTGRES_USER=${SQL_USER}
              - POSTGRES_PASSWORD=${SQL_PASSWORD}
              - POSTGRES_DB=${SQL_NAME}
volumes:
  postgres_data: